### ISSUE TITLE
Is it possible to get the IPA file for the latest tvOS release?

### ISSUE THREAD

**Issue by adrthaaer** [raymon-io/streamcompanionCrossPlatform#1]
I'm currently sideloading an earlier release on my Apple TV, and it's quite bothersome as the chat doesn't appear and there's a white bar at the top. 

I don't have the programming knowledge to compile it myself, nor do I have a Mac. Could you possibly help me with this?

**Comment by raymon-io** [comment]
I haven't updated ios and Apple TV version in a very long time and the chat issue is very new. I really don't know how many people uses ios/Apple TV app so I did not attempt to update it. In my writeups I said, I stopped working on this project and the reason for it but I might decide to update the ios and tvOS and upload the ipa in the github. I cannot promise that I would do it, and personally been pretty busy lately.
I will let you know if I finish the tvOS build with the latest release.

**Comment by raymon-io** [comment]
@Noz0mizore  okay I uploaded the ipa files. Chat issue and the design issue you mentioned is fixed. There might be some small issue here and there like some emotes not showing and the remote does not go to certain buttons well. But you just have to live with it. Already dropped support for all plarforms.
https://github.com/raymon-io/streamcompanionCrossPlatform/releases

**Comment by adrthaaer** [comment]
@raymon-io  Thank you so much! After sideloading, everything works perfectly, and all the issues I mentioned have been resolved

The default chat delay is set to 10 seconds, and unfortunately, I can't reduce it. However, I'm already grateful for what you've provided, so I won't ask for more..
